import { test, expect } from '@playwright/test';
test.use({channel: 'chrome', baseURL: 'http://127.0.0.1:5181', viewport: {width: 1440, height: 1000}, trace: 'retain-on-failure'});
test.setTimeout(60000);

test('outline-only editing, confirmation, generated content and detailed slide creation', async ({page}) => {
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto('/ai-create-course');
  await page.getByPlaceholder('e.g., Introduction to Machine Learning').fill('Outline workflow');
  await page.getByRole('button',{name:'Course design',exact:true}).click();
  await page.getByRole('button',{name:'Quiz',exact:true}).click();
  await page.getByRole('button',{name:'Micro-Learning',exact:true}).click();
  await page.getByRole('button',{name:'Details',exact:true}).click();
  await page.getByRole('button',{name:'Continue',exact:true}).click();
  await page.getByRole('button',{name:'Generate Outline',exact:true}).click();
  await expect(page.getByTestId('outline-slide')).toHaveCount(4);
  await expect(page.getByRole('button',{name:/Preview|Regenerate/})).toHaveCount(0);
  await page.getByRole('button',{name:/Section actions:/}).first().click();
  await expect(page.getByRole('button',{name:'Duplicate',exact:true})).toHaveCount(0);
  await expect(page.getByRole('button',{name:'Reorder',exact:true})).toHaveCount(0);
  await page.getByRole('button',{name:/Section actions:/}).first().click();
  const first = page.getByTestId('outline-slide').first();
  await first.getByTitle('Edit',{exact:true}).click();
  await expect(first.locator('textarea')).toHaveCount(0);
  await expect(first.getByRole('textbox')).toHaveCount(1);
  await first.getByRole('textbox',{name:'Slide name'}).fill('Updated introduction');
  await first.getByRole('button',{name:'Done',exact:true}).click();
  await first.getByTitle('Change slide type',{exact:true}).click();
  await first.getByRole('button',{name:'Spokesperson',exact:true}).click();
  await expect(first.getByText('Spokesperson',{exact:true})).toBeVisible();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button',{name:'Add slide',exact:true}).first().click();
  const drawer = page.getByRole('dialog',{name:'Add outline slide'});
  await expect(drawer.getByRole('textbox')).toHaveCount(0);
  await drawer.getByRole('button',{name:/Title \+ Bullet Points/}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.getByTestId('outline-slide')).toHaveCount(5);
  await page.getByRole('button',{name:'Continue',exact:true}).click();
  const confirmation = page.getByRole('dialog');
  await expect(confirmation.getByTestId('generation-slide-count')).toHaveText('18');
  await expect(page.getByTestId('generated-slide-content')).toHaveCount(0);
  await confirmation.getByRole('button',{name:'Cancel',exact:true}).click();
  await expect(page.getByTestId('outline-slide')).toHaveCount(5);
  await page.getByRole('button',{name:'Continue',exact:true}).click();
  await page.getByRole('button',{name:'Confirm & Generate Content',exact:true}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button',{name:'Continue',exact:true}).click();
  await expect(page.getByTestId('review-slide')).toHaveCount(18);
  await expect(page.getByTestId('generated-slide-content')).toContainText('Updated introduction');
  await page.getByRole('button',{name:'+ Add New Slide',exact:true}).click();
  const details = page.getByRole('dialog',{name:'Slide details'});
  await details.getByRole('button',{name:/Title \+ Text/}).click();
  await expect(details.getByRole('textbox',{name:'Slide title',exact:true})).toBeVisible();
  await details.getByRole('textbox',{name:'Slide title',exact:true}).fill('Manual slide');
  await details.getByPlaceholder('Explain the concept here...').fill('This is the authored slide body.');
  await details.getByRole('button',{name:'Add slide',exact:true}).click();
  await expect(page.getByTestId('review-slide')).toHaveCount(19);
  await page.getByTestId('review-slide').filter({hasText:'Manual slide'}).click();
  await expect(page.getByTestId('generated-slide-content')).toContainText('This is the authored slide body.');
  await page.getByRole('button',{name:'Edit slide content',exact:true}).click();
  await expect(details.getByPlaceholder('Explain the concept here...')).toHaveValue('This is the authored slide body.');
  await details.getByPlaceholder('Explain the concept here...').fill('Saved content after editing.');
  await details.getByRole('button',{name:'Save changes',exact:true}).click();
  await page.getByRole('button',{name:'Preview',exact:true}).click();
  await expect(page.getByTestId('generated-slide-content').last()).toBeVisible();
  // Return from the player using its exit control, then revisit the outline.
  await page.locator('button').filter({has:page.locator('svg.lucide-log-out')}).click();
  await page.getByRole('button',{name:'Back',exact:true}).click();
  await page.getByRole('button',{name:'Back',exact:true}).click();
  await expect(page.getByRole('button',{name:/Preview|Regenerate/})).toHaveCount(0);
  await page.getByRole('button',{name:'Continue',exact:true}).click();
  await expect(page.getByTestId('generation-slide-count')).toHaveText('19');
  await page.getByRole('button',{name:'Confirm & Generate Content',exact:true}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button',{name:'Continue',exact:true}).click();
  await page.getByTestId('review-slide').filter({hasText:'Manual slide'}).click();
  await expect(page.getByTestId('generated-slide-content')).toContainText('Saved content after editing.');
  for (const type of ['Image / Visual', 'Video']) {
    await page.getByRole('button',{name:'+ Add New Slide',exact:true}).click();
    await details.getByRole('button',{name:new RegExp('^' + type)}).click();
    await details.getByRole('textbox',{name:'Slide title',exact:true}).fill(type + ' slide');
    await details.getByRole('button',{name:'Add slide',exact:true}).click();
    await expect(details).toHaveCount(0);
    await expect(page.getByTestId('review-slide').filter({hasText:type + ' slide'})).toBeVisible();
  }
  expect(errors).toEqual([]);
});
