import { test, expect } from '@playwright/test';
test.use({ channel: 'chrome', baseURL: 'http://127.0.0.1:5181', viewport: { width: 1440, height: 1000 } });
test('one common preview combines template and theme in review and expanded player', async ({page}) => {
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto('/ai-create-course');
  await page.getByPlaceholder('e.g., Introduction to Machine Learning').fill('Business communication');
  await page.getByRole('button', {name:'Course design', exact:true}).click();
  await page.getByRole('button', {name:'Quiz', exact:true}).click();
  await page.getByRole('button', {name:'Micro-Learning', exact:true}).click();
  await page.getByRole('button', {name:'Details', exact:true}).click();
  await page.getByRole('button', {name:'Continue', exact:true}).click();
  await page.getByRole('button', {name:'Generate Outline', exact:true}).click();
  await page.getByRole('button', {name:'Continue', exact:true}).click();
  await page.getByRole('button', {name:'Confirm & Generate Content', exact:true}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button', {name:'Continue', exact:true}).click();
  const slide = page.getByTestId('course-presentation');
  await expect(slide).toHaveAttribute('data-template','vivid-blue');
  await expect(slide).toHaveAttribute('data-view','combined');
  await expect(page.getByRole('button', {name:'Template view',exact:true})).toHaveCount(0);
  await expect(page.getByRole('button', {name:'Theme view',exact:true})).toHaveCount(0);
  await slide.screenshot({path:'test-results/review-template.png'});
  await page.getByTestId('review-slide').nth(1).click();
  const title = await slide.locator('h2').innerText();
  await expect(slide).toHaveAttribute('data-view','combined');
  const content = await slide.innerText();
  const style = await slide.getAttribute('style');
  await slide.screenshot({path:'test-results/review-theme.png'});
  await page.getByRole('button',{name:'Preview',exact:true}).click();
  await expect(slide).toHaveCount(2);
  await expect(slide.last().locator('h2')).toHaveText(title);
  expect(await slide.last().innerText()).toBe(content);
  expect(await slide.last().getAttribute('style')).toBe(style);
  await slide.last().screenshot({path:'test-results/expanded-theme.png'});
  expect(errors).toEqual([]);
});
