import { test, expect } from '@playwright/test';
test.use({channel:'chrome',baseURL:'http://127.0.0.1:5181',viewport:{width:1440,height:1000}});
test('design cards apply combined styling and preserve the outline',async({page})=>{
  await page.goto('/ai-create-course');
  await page.getByPlaceholder('e.g., Introduction to Machine Learning').fill('Simplified workflow');
  await page.getByRole('button',{name:'Continue',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Course design',exact:true})).toBeVisible();
  const cards=page.getByTestId('course-design-picker').getByRole('button');
  await expect(cards).toHaveCount(4);
  await expect(page.getByRole('button',{name:'Corporate design',exact:true})).toHaveAttribute('aria-pressed','true');
  await expect(page.getByRole('combobox',{name:'Visual template'})).toHaveCount(0);
  await expect(page.getByText('Colour Combination',{exact:true})).not.toBeVisible();
  await page.getByRole('button',{name:'Modern design',exact:true}).click();
  await expect(page.getByTestId('course-presentation')).toHaveAttribute('data-template','rustic-minimalist');
  await expect(page.getByTestId('course-presentation').locator('.course-slide')).toHaveCSS('background-color','rgb(17, 24, 39)');
  await page.getByRole('button',{name:'Browse all designs',exact:true}).click();
  await expect(cards).toHaveCount(8);
  await page.getByRole('button',{name:'Ocean design',exact:true}).click();
  await page.getByRole('button',{name:'Show fewer designs',exact:true}).click();
  await expect(page.getByRole('button',{name:'Ocean design',exact:true})).toHaveAttribute('aria-pressed','true');
  await page.getByTestId('theme-customization').locator('summary').click();
  await expect(page.getByText('Colour Combination',{exact:true})).toBeVisible();
  await page.getByTestId('theme-customization').locator('summary').click();
  await page.getByRole('button',{name:'Micro-Learning',exact:true}).click();
  await page.getByRole('button',{name:'Generate Outline',exact:true}).click();
  await expect(page.getByTestId('outline-slide')).toHaveCount(4);
  const first=page.getByTestId('outline-slide').first();
  await first.getByTitle('Edit',{exact:true}).click();
  await first.getByRole('textbox',{name:'Slide name'}).fill('Keep my edits');
  await first.getByRole('button',{name:'Done',exact:true}).click();
  await page.getByRole('button',{name:'Back',exact:true}).click();
  await expect(page.getByRole('button',{name:'Ocean design',exact:true})).toHaveAttribute('aria-pressed','true');
  await page.getByRole('button',{name:'Review Outline',exact:true}).click();
  await expect(page.getByTestId('outline-slide').first()).toContainText('Keep my edits');
});