import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
const escape = x => String(x ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function renderReport(directory) {
  const issues=JSON.parse(readFileSync(resolve(directory,'issues.json')));
  const run=JSON.parse(readFileSync(resolve(directory,'run.json')));
  const measurements=JSON.parse(readFileSync(resolve(directory,'measurements.json')));
  const active=issues.filter(x=>x.status!=='dismissed');
  const order={critical:0,high:1,medium:2,low:3};
  const image=(o,cls='')=>`<button class="image ${cls}" data-src="${escape(o.screenshot)}" aria-label="Enlarge evidence ${escape(o.id)}"><img src="${escape(o.screenshot)}" alt="${escape(o.id)}: ${escape(o.label||'measured issue evidence')}"></button>`;
  let body='';
  for(const page of [...new Set(active.map(x=>x.page))]){
    body+=`<section><h2>${escape(page)}</h2>`;
    for(const issue of active.filter(x=>x.page===page).sort((a,b)=>order[a.severity]-order[b.severity])){
      body+=`<article id="${escape(issue.id)}"><div class="evidence">${image(issue.occurrences[0],'primary')}${issue.occurrences.length>1?`<div class="strip" aria-label="Per-occurrence evidence">${issue.occurrences.map(o=>image(o)).join('')}</div>`:''}</div><div class="details"><div class="tags"><b class="${escape(issue.severity)}">${escape(issue.severity)}</b> ${escape(issue.category)} · ${issue.occurrences.length} occurrence${issue.occurrences.length===1?'':'s'} · ${escape(issue.status)}</div><h3>${escape(issue.description)}</h3><p><strong>Expected:</strong> ${escape(issue.expected)}</p><p><strong>Actual:</strong> ${escape(issue.actual)}</p>${issue.spacing?`<p class="math">${escape(issue.spacing.arithmetic)}</p><p>Proposed ${escape(issue.spacing.rhythm.name)}: ${issue.spacing.rhythm.values.join(' / ')}px</p>`:''}<ul class="locations">${issue.occurrences.map(o=>`<li>${escape(o.file)}:${o.line??'?'} <span>${escape(o.label)}</span>${o.fallbackReason?` — fallback: ${escape(o.fallbackReason)}`:''}</li>`).join('')}</ul><small>${escape(issue.id)} · ${issue.viewport.width} × ${issue.viewport.height}</small></div></article>`;
    }body+='</section>';
  }
  const occurrences=active.flatMap(i=>i.occurrences);const cropped=occurrences.filter(o=>o.evidence==='annotated-crop').length;
  body+='<section><h2>Spacing evidence</h2><p>Every measured adjacent pair has its own live band capture. Correct gaps are evidence, not manufactured issues.</p>';
  for(const measured of measurements){const counts=measured.gaps.reduce((a,g)=>(a[g.classification]=(a[g.classification]||0)+1,a),{});body+=`<details><summary>${escape(measured.page)}: ${measured.gaps.length} pairs — ${escape(JSON.stringify(counts))}</summary><div class="strip">${measured.gaps.map((g,i)=>image({id:'gap-'+(i+1),screenshot:g.screenshot,label:g.arithmetic})).join('')}</div></details>`;}body+='</section>';
  writeFileSync(resolve(directory,'review-report.html'),`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Design review — ${escape(run.pages.join(', '))}</title><style>
  *{box-sizing:border-box}body{margin:0;background:#f4f6f9;color:#182337;font:15px/1.55 system-ui,sans-serif}header,main{max-width:1320px;margin:auto;padding:28px}header{padding-bottom:0}h1{margin:0;font-size:32px}h2{margin:30px 0 14px}h3{margin:10px 0;font-size:20px}.note{padding:14px 18px;background:#fff3d5;border-left:4px solid #b57000}.summary{color:#46546a}article{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:24px;background:white;border:1px solid #dbe1ea;border-radius:12px;padding:24px;margin-bottom:20px}.evidence{min-width:0}.image{display:block;border:1px solid #c3ccda;background:#eef2f6;padding:4px;cursor:zoom-in;border-radius:5px}.primary{width:100%}.primary img{display:block;width:100%;height:auto}.strip{display:flex;gap:8px;overflow-x:auto;margin-top:12px;padding:4px 0 10px}.strip .image{flex:0 0 auto}.strip img{display:block;height:82px;width:auto;max-width:none;object-fit:contain}.tags{font-size:12px;text-transform:uppercase;letter-spacing:.04em}.tags b{padding:3px 7px;border-radius:4px}.high,.critical{color:#9f1239;background:#ffe4e6}.medium{color:#854d0e;background:#fef3c7}.low{color:#1e40af;background:#dbeafe}p{margin:10px 0}.locations{padding-left:18px;font:12px/1.7 ui-monospace,monospace;overflow-wrap:anywhere}.locations span{color:#64748b}.math{font-family:ui-monospace,monospace;font-size:13px}dialog{border:0;background:#101827;color:white;max-width:none;max-height:none;width:100vw;height:100vh;padding:64px 32px 32px}dialog::backdrop{background:#101827}dialog .stage{display:flex;align-items:center;justify-content:center;height:100%;pointer-events:none}dialog img{max-width:94vw;max-height:86vh;object-fit:contain;pointer-events:auto;image-rendering:auto}#close{position:absolute;right:24px;top:14px;background:white;color:#101827;border:0;border-radius:6px;padding:8px 16px;font-size:24px;cursor:pointer}a{color:#174db1}small{color:#66758d}
  .primary img{max-height:300px;object-fit:contain}dialog img{width:100%;height:100%}</style><header><h1>Design review</h1><p class="summary">${escape(run.pages.join(', '))} · desktop 1440 × 1000 · ${active.length} issues · ${cropped}/${occurrences.length} occurrences have annotated crops · ${escape(run.createdAt)}</p><p class="note">${escape(run.baselineNote)}</p><p><a href="issues.json">Issues JSON</a> · <a href="measurements.json">Exact spacing measurements</a> · <a href="run.json">Run provenance</a></p></header><main>${body||'<p>No confirmed issues in this scope.</p>'}</main><dialog id="zoom" aria-label="Full screen evidence viewer"><button id="close" aria-label="Close evidence">✕</button><div class="stage"><img id="zoom-image" alt="Enlarged annotated evidence"></div></dialog><script>
  const modal=document.getElementById('zoom');let opener;
  document.querySelectorAll('[data-src]').forEach(button=>button.addEventListener('click',()=>{opener=button;document.getElementById('zoom-image').src=button.dataset.src;modal.showModal();document.getElementById('close').focus();}));
  document.getElementById('close').onclick=()=>modal.close();
  modal.addEventListener('click',e=>{if(e.target===modal)modal.close();});
  modal.addEventListener('close',()=>opener?.focus());
  </script></html>`);
  return {issues:active.length,occurrences:occurrences.length,cropped,fallbacks:occurrences.length-cropped};
}
